### ISSUE TITLE
[pytket-qsharp] Use `actions/setup-dotnet` in CI workflows.

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-extensions#188]
Instead of installing dotnet SDK in different ways on different platforms, we can just use:
```
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
```
in the workflow scripts.
